# Anyone compiling mbedTLS code needs the name of the
# alternative config file
CFLAGS += -DMBEDTLS_CONFIG_FILE='"mbedtls/esp_config.h"'
CFLAGS += -DMBEDTLS_USER_CONFIG_FILE='"mbedtls/user_config.h"'

